# Generated by Django 4.2.2 on 2023-06-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avocado_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avocado_Prices',
            new_name='Avocado_Price',
        ),
    ]
