# Generated by Django 4.2.2 on 2023-07-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avocado_data', '0002_rename_avocado_prices_avocado_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_House_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('average_price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='avocado_price',
            name='region',
        ),
        migrations.AddField(
            model_name='avocado_price',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avocado_data.city_house_price'),
        ),
    ]
