# Generated by Django 4.2.2 on 2023-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocado_data', '0003_city_house_price_remove_avocado_price_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city_house_price',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='city_house_price',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
